export const SET_RESOURCES = 'SET_RESOURCES';
export const FETCH_RESOURCES_FAILED = 'FETCH_RESOURCES_FAILED';
export const INIT_RESOURCES = 'INIT_RESOURCES';

export const FETCH_RESOLUTIONS_FAILED = 'FETCH_RESOLUTIONS_FAILED'
export const FETCH_RESOLUTIONS_SUCCESS = 'FETCH_RESOLUTIONS_SUCCESS';
export const FETCH_RESOLUTIONS_START = 'FETCH_RESOLUTIONS_START';


export const REMOVE_RESOLUTION = 'REMOVE_RESOLUTION';
// export const ADD_RESOLUTION = 'ADD_RESOLUTION';
